/**
 * @file    cave_scene.h
 * @authors Savin A.     <telvina<at>student.21-school.ru
 * @authors Degtyarev A. <sreanna<at>student.21-school.ru>
 * @date    23/08/22
 */

#ifndef CAVE_SCENE_H
#define CAVE_SCENE_H

#include <QWidget>
#include <QPaintEvent>

#include <memory>

#include "../model/core/matrix.h"
#include "../model/core/core.h"
#include"../controller/controller.h"

/**
 * @class CaveScene
 * @brief Class draws caves that generated by model
 */

class CaveScene final : public QWidget
{
    Q_OBJECT
    Q_DISABLE_COPY_MOVE(CaveScene)

public:
    explicit CaveScene(QWidget *parent = nullptr);
    ~CaveScene() final = default;

public:
    auto SetController(const std::shared_ptr<s21::Controller>& controller) -> void;

private:
    auto paintEvent(QPaintEvent* event) -> void override;

private:
    std::shared_ptr<s21::Controller> m_controller {};
    s21::Matrix<bool>                m_cells {};
    s21::Mode                        m_mode  {};
    int                              m_rows {};
    int                              m_cols {};

private:
    static constexpr double windowSize {500};

};

#endif // CAVE_SCENE_H
